In [73]:
import pandas as pd
import datetime
import numpy as np
pd.set_option('display.max_rows', 200)
data = pd.read_csv('melb_data.csv')

In [74]:
#1.check null values
data.isnull().sum().sort_values(ascending = False)

BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Car                62
Propertycount       0
Date                0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Bedroom2            0
Distance            0
Postcode            0
Regionname          0
Bathroom            0
Landsize            0
Lattitude           0
Longtitude          0
Suburb              0
dtype: int64

In [75]:
#2.fill the null values.
data['Car'] = data['Car'].fillna(0)
data['BuildingArea'] = data['BuildingArea'].fillna(data['BuildingArea'].median)
data['YearBuilt'] = data['YearBuilt'].fillna(data['YearBuilt'].median)
data['CouncilArea'] = data['CouncilArea'].fillna(method = 'ffill')

In [76]:
data

Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S   
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2         Abbotsford      5 Charles St      3    h  1465000.0     SP   
3         Abbotsford  40 Federation La      3    h   850000.0     PI   
4         Abbotsford       55a Park St      4    h  1600000.0     VB   
...              ...               ...    ...  ...        ...    ...   
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S   
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP   
13577   Williamstown       83 Power St      3    h  1170000.0      S   
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI   
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP   

        SellerG        Date  Distance  Postcode  Bedroom2  Bathroom  Car  \
0        Biggin   3/12/2016       2.5    3067.0       2.0       1.0  1.0   
1        Biggin   4/02/2016       2.5    3067.0       2.0       1.0  0.0   
2        Biggin   4/03/2017       2.5    3067.0       3.0       2.0  0.0   
3        Biggin   4/03/2017       2.5    3067.0       3.0       2.0  1.0   
4        Nelson   4/06/2016       2.5    3067.0       3.0       1.0  2.0   
...         ...         ...       ...       ...       ...       ...  ...   
13575     Barry  26/08/2017      16.7    3150.0       4.0       2.0  2.0   
13576  Williams  26/08/2017       6.8    3016.0       3.0       2.0  2.0   
13577     Raine  26/08/2017       6.8    3016.0       3.0       2.0  4.0   
13578   Sweeney  26/08/2017       6.8    3016.0       4.0       1.0  5.0   
13579   Village  26/08/2017       6.3    3013.0       4.0       1.0  1.0   

       Landsize                                       BuildingArea  \
0         202.0  <bound method Series.median of 0          NaN\...   
1         156.0                                                 79   
2         134.0                                                150   
3          94.0  <bound method Series.median of 0          NaN\...   
4         120.0                                                142   
...         ...                                                ...   
13575     652.0  <bound method Series.median of 0          NaN\...   
13576     333.0                                                133   
13577     436.0  <bound method Series.median of 0          NaN\...   
13578     866.0                                                157   
13579     362.0                                                112   

                                               YearBuilt  CouncilArea  \
0      <bound method Series.median of 0           NaN...        Yarra   
1                                                   1900        Yarra   
2                                                   1900        Yarra   
3      <bound method Series.median of 0           NaN...        Yarra   
4                                                   2014        Yarra   
...                                                  ...          ...   
13575                                               1981  Maribyrnong   
13576                                               1995  Maribyrnong   
13577                                               1997  Maribyrnong   
13578                                               1920  Maribyrnong   
13579                                               1920  Maribyrnong   

       Lattitude  Longtitude                  Regionname  Propertycount  
0      -37.79960   144.99840       Northern Metropolitan         4019.0  
1      -37.80790   144.99340       Northern Metropolitan         4019.0  
2      -37.80930   144.99440       Northern Metropolitan         4019.0  
3      -37.79690   144.99690       Northern Metropolitan         4019.0  
4      -37.80720   144.99410       Northern Metropolitan         4019.0  
...          ...         ...                         ...            ...  


In [78]:
#3. process the time information
data['Date'] = pd.to_datetime(data['Date'],format='%d/%m/%Y')
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data

Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S   
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2         Abbotsford      5 Charles St      3    h  1465000.0     SP   
3         Abbotsford  40 Federation La      3    h   850000.0     PI   
4         Abbotsford       55a Park St      4    h  1600000.0     VB   
...              ...               ...    ...  ...        ...    ...   
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S   
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP   
13577   Williamstown       83 Power St      3    h  1170000.0      S   
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI   
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP   

        SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  \
0        Biggin 2016-12-03       2.5    3067.0       2.0       1.0  1.0   
1        Biggin 2016-02-04       2.5    3067.0       2.0       1.0  0.0   
2        Biggin 2017-03-04       2.5    3067.0       3.0       2.0  0.0   
3        Biggin 2017-03-04       2.5    3067.0       3.0       2.0  1.0   
4        Nelson 2016-06-04       2.5    3067.0       3.0       1.0  2.0   
...         ...        ...       ...       ...       ...       ...  ...   
13575     Barry 2017-08-26      16.7    3150.0       4.0       2.0  2.0   
13576  Williams 2017-08-26       6.8    3016.0       3.0       2.0  2.0   
13577     Raine 2017-08-26       6.8    3016.0       3.0       2.0  4.0   
13578   Sweeney 2017-08-26       6.8    3016.0       4.0       1.0  5.0   
13579   Village 2017-08-26       6.3    3013.0       4.0       1.0  1.0   

       Landsize                                       BuildingArea  \
0         202.0  <bound method Series.median of 0          NaN\...   
1         156.0                                                 79   
2         134.0                                                150   
3          94.0  <bound method Series.median of 0          NaN\...   
4         120.0                                                142   
...         ...                                                ...   
13575     652.0  <bound method Series.median of 0          NaN\...   
13576     333.0                                                133   
13577     436.0  <bound method Series.median of 0          NaN\...   
13578     866.0                                                157   
13579     362.0                                                112   

                                               YearBuilt  CouncilArea  \
0      <bound method Series.median of 0           NaN...        Yarra   
1                                                   1900        Yarra   
2                                                   1900        Yarra   
3      <bound method Series.median of 0           NaN...        Yarra   
4                                                   2014        Yarra   
...                                                  ...          ...   
13575                                               1981  Maribyrnong   
13576                                               1995  Maribyrnong   
13577                                               1997  Maribyrnong   
13578                                               1920  Maribyrnong   
13579                                               1920  Maribyrnong   

       Lattitude  Longtitude                  Regionname  Propertycount  Year  \
0      -37.79960   144.99840       Northern Metropolitan         4019.0  2016   
1      -37.80790   144.99340       Northern Metropolitan         4019.0  2016   
2      -37.80930   144.99440       Northern Metropolitan         4019.0  2017   
3      -37.79690   144.99690       Northern Metropolitan         4019.0  2017   
4      -37.80720   144.99410       Northern Metropolitan         4019.0  2016   
...          ...         ...                

In [85]:
#4. check years
data['Year'].unique()

array([2016, 2017], dtype=int64)

In [95]:
#4.1 check the months for evey year
df1=data[data['Year']==2016]
df1['Month'].unique()
# array_df1 = df1['Month'].unique().sort()
# array_df1=np.array(df1['Month'].unique())
# array_df1 = array_df1.argsort()
# array_df1
# Mar is missed.

array([12,  2,  6,  5, 10, 11,  8,  7,  9,  4,  1], dtype=int64)

In [87]:
#4.2 check the months for evey year
df2=data[data['Year']==2017]
df2['Month'].unique()
#Jan, may, Oct, Nov, Dec are missed.

array([3, 2, 5, 4, 7, 6, 8, 9], dtype=int64)